### PR TITLE
Change width of model service table columns

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Changed the width of the columns in the models and signing keys tables to better fit the content

## How to QA
- Go to https://snapcraft-io-4374.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/models
- Check that the table columns fit the content more appropriately
- **Note**: The space between the name and API key looks a bit weird, but we have to mask the API key so not sure what the best solution to this would be?
- Go to https://snapcraft-io-4374.demos.haus/admin/njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26/signing-keys
- Check that the table columns fit the content more appropriately

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-5639

### CODE REVIEW

**Review by codeEmpress1 — DISMISSED** [review]

**Comment by Lukewh** [comment]
Looks like the table is cut off:

image

**Comment by steverydz** [comment]
@Lukewh I've increased the width of the column by 20px. Is it any better? I'm not getting the issue myself so I can't tell?

**Comment by Lukewh** [comment]
> @Lukewh I've increased the width of the column by 20px. Is it any better? I'm not getting the issue myself so I can't tell?

Yeah that's fixed it :+1:

**Comment by julpal7** [comment]
@steverydz when I preview the Models page in wider resolutions, the "policy revision" breaks into two lines. (It opens that way by default on both my laptop and connected 4k display)

snapcraft-io-4374 demos haus_admin_njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26_models (3)

Maybe you could change the column width to 150px, for example? It spreads them out a bit more evenly and fixes the text issue.
snapcraft-io-4374 demos haus_admin_njwQYXFnS7ppo7LaGxoh7aqVZc1CPi26_models (4)

**Comment by steverydz** [comment]
@julpal7 I've updated it. Is this better?

**Comment by julpal7** [comment]
@steverydz it is, thank you!

**Review by Lukewh — APPROVED** [review]

**Pull request merged**
