### PR TITLE
feat: updated csp

### LINKED ISSUE #4850: Previously working GIFs no longer appear
### Expected behaviour

Visit https://snapcraft.io/syft and https://snapcraft.io/grype and see an animated GIF at the top.

### Steps to reproduce the problem

* Visit https://snapcraft.io/syft and https://snapcraft.io/grype
* Expect to see a GIF I previously uploaded (months ago)
* Actually see no GIF

### Screenshots

**Internal store page showing uploaded media**

image

**Public store page showing no media**

image

### Specs

- _URL:_ https://snapcraft.io/syft 
- _Operating system:_ macOS Sonoma 14.6.1
- _Browser:_ Microsoft Edge Version 128.0.2739.67 (Official build) (arm64)

- [X] This issue is related to the snapcraft.io website itself (and not a specific snap).

### PR DESCRIPTION
**Pull request by ilayda-cp**
## Done
Added the missing csp

## How to QA
- go to https://snapcraft-io-4852.demos.haus/grype
- Verify the gif is loaded correctly
- go to https://snapcraft-io-4852.demos.haus/syft
- Verify the gif is loaded correctly

## Testing
- [ ] This PR has tests
- [x] No testing required (explain why): Added a security header

## Issue / Card
Fixes [#14936](https://warthogs.atlassian.net/browse/WD-14936)
Fixes #4850

### CODE REVIEW

**Review by Lukewh — APPROVED** [review]
:+1: LGTM

**Comment by IlyaBizyaev** [comment]
I believe this change broke Snap download buttons in KDE's apps catalog, for example, on https://apps.kde.org/dolphin/. 

How can they be fixed, respecting localization? (e.g. https://snapcraft.io/static/images/badges/de/snap-store-black.svg)

**Comment by ilayda-cp** [comment]
Hey @IlyaBizyaev could you try to add crossorigin="anonymous" like displayed in here:

``

Let me know if this solution doesn't work.

**Comment by PhuNH** [comment]
The attribute has been added, but the request still fails with [Reason: CORS Missing Allow Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin). Could you do something about that?

**Comment by ilayda-cp** [comment]
Hello @PhuNH thanks for reaching out. We fixed the previous problem so you don't need to add crossorigin="anonymous" . But it looks like you are trying to access the website resource directly. This is why security headers blocks it. We suggest you to use the badge instead. For example for the given snap it looks like this:

https://snapcraft.io/dolphin/badge.svg

Let me know if you have any questions.

**Comment by IlyaBizyaev** [comment]
This "badge" doesn't look like the typical "Install from X" store badges at all, we can't really use it...

See e.g. https://flathub.org/badges for how other stores provide their badge images to developers. 

(the previous badges worked great before being declared internal resources)

**Comment by PhuNH** [comment]
https://snapcraft.io/about/publicise tells us to use your “Get it from the snap store” badge, and that's what we want, not the "GitHub badge" which you linked to. Could you tell where we can access such badges?

**Comment by ilayda-cp** [comment]
Thank you for your feedback @IlyaBizyaev and @PhuNH. I understand your need and we will work on it.

**Comment by PhuNH** [comment]
Thanks @ilayda-cp

**Pull request merged**
