### PR TITLE
feat: build /iot page

### PR DESCRIPTION
**Pull request by chillkang**
## Done
- Built /iot page according to the copy doc 

## How to QA
- Go to https://snapcraft-io-4815.demos.haus/iot and compare the page with the [copy doc](https://docs.google.com/document/d/1xP7yt-pVoKNCnV0eRoex6VitHN5SilDR5ArglKzlpUg/edit)

## Testing
- [ ] This PR has tests
- [x] No testing required (explain why): design changes

## Issue / Card
Fixes #https://warthogs.atlassian.net/browse/WD-6472

### CODE REVIEW

**Comment by AnnSoMuller** [comment]
For the layout, 

1. For the top part, use https://vanillaframework.io/docs/patterns/hero 

- even if we don't have an image yet
- title and paragraph (no subtitle)
- for CTA, use https://vanillaframework.io/docs/patterns/cta-block
Main CTA "[Get started with IoT](https://ubuntu.com/internet-of-things)] 

2. For the content, use the [25% rule](https://vanillaframework.io/docs/layouts/brochure).
to look like:
Screenshot 2024-08-21 at 11 37 59

**Comment by chillkang** [comment]
> A couple of discrepancies with the copy doc.
> 
> In "Do more with your devices":
> 
> * Node-RED and Zwave JS UI have wrong icon
> * Node-RED should link to https://snapcraft.io/publisher/noderedteam according to the copy doc
> 
> In "Learn more about our IoT offerings"
> 
> * mosquitto should link to https://snapcraft.io/publisher/mosquitto according to the copy doc

@steverydz Changed the snap icons! I think the publisher links are the correct ones but let me know if there are any issues.

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by AnnSoMuller** [comment]
1. Much better for the banner area, but the line on top of action is missing
ours:
Screenshot 2024-08-21 at 17 45 27
in [vanilla](https://vanillaframework.io/docs/patterns/hero)
Screenshot 2024-08-21 at 17 44 48

2. I still don't see the 25% split for the layout
what I see
Screenshot 2024-08-21 at 17 41 12
how it should look like :)
Screenshot 2024-08-21 at 17 43 12

**Comment by AnnSoMuller** [comment]
@chillkang I have done a sketch for a better understanding 
Screenshot 2024-08-22 at 10 26 23

**Comment by chillkang** [comment]
@AnnSoMuller Thanks for your clarification! Could you have a look at the new demo?

**Comment by AnnSoMuller** [comment]
Hi @chillkang few more changes and it should be ok :)
looking at vanilla 
(https://vanillaframework.io/docs/layouts/brochure)
(https://vanillaframework.io/docs/patterns/tiered-list)
and Charmhub pages (https://juju.is/why-juju), I think :

- the <h4> you used should be <h5> 
- lines are missing between sections
- we should use the same layout for the "learn more" part

Thanks

**Pull request merged**
