### PR TITLE
feat: Show domain verified status on snap page

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Added the verification notification to the primary domain on the snap page

## How to QA
- Go to https://snapcraft-io-4724.demos.haus/steve-test-snap
- Check that there is a verified domain icon and tooltip next to the first domain under "Websites"
- Go to https://snapcraft-io-4724.demos.haus/code (or any other snap)
- Check that there is NOT a verified domain icon and tooltip next to the first domain under "Websites"

## Testing
- [ ] This PR has tests
- [x] No testing required (explain why): Small UI change

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-12525

### CODE REVIEW

**Review by chillkang — APPROVED** [review]
LGTM👍

**Comment by AnnSoMuller** [comment]
Just the colour of the icon should be the same than the label. It looks kind of blue for now

**Comment by steverydz** [comment]
> Just the colour of the icon should be the same than the label. It looks kind of blue for now

@AnnSoMuller This icons is as in Vanilla (https://vanillaframework.io/docs/patterns/icons#alert). Perhaps the question mark icon would be more appropriate? The tooltip is essentially answering a question.

**Comment by AnnSoMuller** [comment]
Hi @steverydz In vanilla the icon is the "right" color 
Screenshot 2024-07-01 at 09 06 12
to follow :)
Not sure why it is blue in the page.
We can keep the information icon.
here it is how I see it in the demo page
Screenshot 2024-07-01 at 09 08 31

**Comment by steverydz** [comment]
@AnnSoMuller The version of vanilla we are on currently has the icons as blue. I've just updated it for this PR so should be fine now.

**Comment by AnnSoMuller** [comment]
Top!

**Pull request merged**
