### PR TITLE
feat(publishers): Publisher pages

### PR DESCRIPTION
**Pull request by Lukewh**
## Done
- Added publisher pages for all publishers

## How to QA
- Visit https://snapcraft-io-4174.demos.haus/publisher/kde, https://snapcraft-io-4174.demos.haus/publisher/jetbrains, https://snapcraft-io-4174.demos.haus/publisher/snapcrafters and ensure they all work as expected (as before).
- Visit https://snapcraft-io-4174.demos.haus/publisher/lukewh, ensure the most important snaps in the snap universe are listed
- Visit https://snapcraft-io-4174.demos.haus/publisher/spotify, ensure only 1 snap is listed - spotify. Also see that the verified publisher icon is shown
- Visit https://snapcraft-io-4174.demos.haus/publisher/imamadeuppublisher, see that there are 0 snaps
- Visit https://snapcraft-io-4174.demos.haus/publisher/mvo and see that the star developer icon is shown

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-954

## Screenshots
image

image

image

### CODE REVIEW

**Comment by codeEmpress1** [comment]
- Visit https://snapcraft-io-4174.demos.haus/publisher/mvo and see that the star developer icon is shown

Only the first snap has the icon displayed, others just have the placeholder, Is that for the star developer? Not sure if that's how it's intended. Other than that, everything looks good to me.

**Comment by Lukewh** [comment]
> * Visit [snapcraft-io-4174.demos.haus/publisher/mvo](https://snapcraft-io-4174.demos.haus/publisher/mvo) and see that the star developer icon is shown
> 
> Only the first snap has the icon displayed, others just have the placeholder, Is that for the star developer? Not sure if that's how it's intended. Other than that, everything looks good to me.

Yeah MVO only added an icon for the first snap :)

**Comment by Lukewh** [comment]
> The only thing I see is that the colors of the headers are different depending on the page (black or gray) and at some point they are the same color as the navigation bar. But once we change the navigation bar we should probably revisit those headers (also as part of the rebranding). Can we at least use the same color for all headers? Or is there a reason why they are different?

We actually use 2 colours, do you think it should be:
https://snapcraft.io/krita or https://snapcraft.io/publisher/kde

**Comment by AnnSoMuller** [comment]
UX +1

**Pull request merged**
