### PR TITLE
Add expandable nav to docs

### LINKED ISSUE #4184: snapcraft.io/docs: Update to add expandable navigation
Can we update https://snapcraft.io/docs to include expandable navigation, as currently used on most of our other documentation sites.

For reference, previous requests for other docs include:
https://github.com/canonical/ubuntu.com/issues/12026 (Ubuntu Core)
https://github.com/canonical/microk8s.io/issues/553 (microK8s).

Thank you!

### PR DESCRIPTION
**Pull request by Lukewh**
## Done
- Removed unused files
- Deduped some of the code
- Implemented expandable navigation

## How to QA
- Visit https://snapcraft-io-4192.demos.haus/docs and ensure everything works as expected.
- Also ensure the search results page looks OK
- Make sure things are as expected on mobile

## Issue / Card
Fixes #4184 
and https://warthogs.atlassian.net/browse/WD-1135

### CODE REVIEW

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by degville** [comment]
Thanks so much for doing this. It looks good to me too. Can I ask that it doesn't go live Friday PM (in case that was planned). It'll be easier to respond to any potential problems/edit for clarity after the weekend. Thanks again.

**Comment by Lukewh** [comment]
> Thanks so much for doing this. It looks good to me too. Can I ask that it doesn't go live Friday PM (in case that was planned). It'll be easier to respond to any potential problems/edit for clarity after the weekend. Thanks again.

Yeah no worries, I'll merge it now, but we won't deploy until Monday now anyway :+1:

**Comment by Lukewh** [comment]
> Thanks so much for doing this. It looks good to me too. Can I ask that it doesn't go live Friday PM (in case that was planned). It'll be easier to respond to any potential problems/edit for clarity after the weekend. Thanks again.

This has now been deployed :)

**Pull request merged**
