### PR TITLE
Rebrand vanilla 4

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Upgraded to Vanilla 4 and updated the design

## QA
Visit:
- https://snapcraft-io-4258.demos.haus/
- https://snapcraft-io-4258.demos.haus/build
- https://snapcraft-io-4258.demos.haus/code
- https://snapcraft-io-4258.demos.haus/about
- https://snapcraft-io-4258.demos.haus/about/publish
- https://snapcraft-io-4258.demos.haus/about/listing
- https://snapcraft-io-4258.demos.haus/about/release
- https://snapcraft-io-4258.demos.haus/about/publicise
- https://snapcraft-io-4258.demos.haus/iot
- https://snapcraft-io-4258.demos.haus/store

Compare to [designs](https://app.zeplin.io/project/64107f86ec62b30f2acff2de/dashboard?sid=641087e78599900fe90c1436)

## Issue
Fixes https://warthogs.atlassian.net/browse/WD-3697

### CODE REVIEW

**Comment by steverydz** [comment]
@lyubomir-popov Can you please give these pages a design review? One thing to note is the suru on the homepage doesn't quite match the default strip colour. Should we override the strip of do we need a new image?

**Comment by lyubomir-popov** [comment]
Hi @steverydz I need to plan some time to review this, would it be ok if we do it next week - e.g. for Thursday?

**Comment by steverydz** [comment]
@lyubomir-popov Yeah, that's fine

**Comment by Lukewh** [comment]
This is currently blocked on the survey being set up to be embedded in the new site.

**Pull request merged**
