### PR TITLE
Adds "Add track" functionality

### PR DESCRIPTION
**Pull request by abbiesims**
## Done

Allows users to add a new track to a snap that already has more than one track. Users will receive a successful or unsuccessful message depending on the outcome.

## How to QA

- Go to a Snap release page that already has more than one track (e.g. https://snapcraft-io-4596.demos.haus/fran-snap/releases)
- Verify that the side panel opens with add track options
- If you have permissions to add a track to the Snap, try and add a new track and verify that it works
- Otherwise, see screenshots below

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-10155

## Screenshots

Screenshot from 2024-04-15 10-44-14
Screenshot from 2024-04-15 10-44-32
Screenshot from 2024-04-15 10-48-28
Screenshot from 2024-04-15 10-50-46
Screenshot from 2024-04-15 10-50-57

### CODE REVIEW

**Comment by Lukewh** [comment]
Is it possible to switch to the newly created track and close the side panel when a track is created successfully?

**Comment by abbiesims** [comment]
Yep, sure. Do you still want to show a success message as well?

**Comment by abbiesims** [comment]
@Lukewh added those fixes and put the "Success" notification on the main page as the side panel will close

**Comment by AnnSoMuller** [comment]
Good! Just few comments:

- Can we follow the Vanilla pattern for errors about the track name (under "Validation"[ here](https://vanillaframework.io/docs/base/forms) 
- The list of tracks follows V.1, V.10, V.11, V.2, V20 etc. Can not it be V.1, V.2, V.3, (...), V.9, V.10, V.11 etc. ?
- +1 on Luke comment with a toast message for the creation :)

**Comment by Lukewh** [comment]
> Yep, sure. Do you still want to show a success message as well? (on the Snap page somewhere, not within the side panel if we are closing it)

Yeah that makes sense to show as a notification on the release page at the top :+1:

**Comment by abbiesims** [comment]
@Lukewh @AnnSoMuller comments have been addressed!

- Vanilla validation within the form

Screenshot from 2024-04-16 08-37-09
Screenshot from 2024-04-16 08-37-27

- Success message on main page

Screenshot from 2024-04-15 15-52-40

- Track listing fixed to be numerical

Screenshot from 2024-04-16 08-56-16

**Comment by AnnSoMuller** [comment]
🚀

**Review by Lukewh — APPROVED** [review]
:+1: LGTM

**Pull request merged**
