### PR TITLE
Update brand store snaps view

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Applied [new design](https://app.zeplin.io/project/659574cda0730e724877bf7d/screen/65ccf575c11ebde092e501cf) to brand store snaps view

## How to QA
- Go to https://snapcraft-io-4559.demos.haus/admin
- Check that the tables for published and included snaps are inside accordions

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-9515

### CODE REVIEW

**Review by chillkang — APPROVED** [review]
LGTM👍

**Comment by codeEmpress1** [comment]
LGTM!

**Review by codeEmpress1 — APPROVED** [review]

**Comment by AnnSoMuller** [comment]
I have few comments, not sure if this PR should content all of them but for to make sure we are not missing anything here they are:

1. In the Store snap section, we are missing the section about registering snap names (that we currently only have in "my snaps"
2. We are missing links for all snap when relevant, as explained in [that wireframe](https://app.zeplin.io/project/659574cda0730e724877bf7d/screen/659ec20ddd0a5c0f155c441a)
e.g if I add my snap "test-annso" to a store, we I click on its link, I should then go to https://snapcraft.io/test-anneso/listing instead of https://snapcraft.io/test-anneso
3. Buttons within sections should be aligned with the title, it is more obvious in this visual part:
Screenshot 2024-03-21 at 09 43 21
Screenshot 2024-03-21 at 09 47 15
4. When adding a snap, in the side panel, the search has a really small height for the list (that grows when we add snaps
Screenshot 2024-03-21 at 09 34 45

**Comment by steverydz** [comment]
@AnnSoMuller The "Register snap name" and the list of registered snap names will be specific to the logged in user and not the store that the user is in, so not everyone in the store is going to see the same list of snaps. Is that what we want here?

**Comment by steverydz** [comment]
@AnnSoMuller I've updated the links and moved the buttons over the accordion toggle button. I've had to use dense buttons in order to keep them within the bounds of the accordion toggle.

I've left the registered snaps for now as we discussed earlier.

**Comment by AnnSoMuller** [comment]
That's great!
@steverydz however, links to snap listing pages are going away from the app layout. Is it suppose to be another PR?
Thanks

**Comment by steverydz** [comment]
@lyubomir-popov Would you please be able to give this a visual review?

**Pull request merged**
