### PR TITLE
Add track dropdown on all Snap release pages

### PR DESCRIPTION
**Pull request by abbiesims**
## Done
Adds custom dropdown box to view tracks for all Snaps, even if they only have one. Displays Default label to show Default track, and tick icon to show which track the user is currently viewing.

## How to QA
https://snapcraft-io-4573.demos.haus/fran-snap/releases and check Tracks dropdown. 
Alternatively, navigate to any Snap release page and check Tracks dropdown.

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-10009

### CODE REVIEW

**Review by chillkang — APPROVED** [review]
LGTM👍

**Comment by Lukewh** [comment]
Can we add a max height to the dropdown? When checking snaps like https://snapcraft-io-4573.demos.haus/lxd/releases the dropdown extends past the bottom of the page

**Comment by abbiesims** [comment]
> Can we add a max height with a scroll to the dropdown? When checking snaps like https://snapcraft-io-4573.demos.haus/lxd/releases the dropdown extends past the bottom of the page

@Lukewh sure, done, let me know if it looks okay

**Comment by Lukewh** [comment]
:+1: LGTM

**Pull request merged**
